name: Consolidated Video Processing
on:
  workflow_dispatch:
  schedule:
    - cron: "0 */6 * * *"
jobs:
  process:
    if: false
    runs-on: ubuntu-latest
    steps:
      - run: echo "Workflow disabled"